### ISSUE TITLE
CPU Support Request (AMD OPTERON)

### ISSUE THREAD

**Issue by JasonBucotte** [JohnTheRaptor/cpuminer-gr-rtm#1]
I thought I'd ask if you could release a version for AMD Opteron CPU's, 6300 and 4300 series.
[https://developer.amd.com/wordpress/media/2012/10/CompilerOptQuickRef-63004300.pdf]

**Comment by JohnTheRaptor** [comment]
That is Bulldozer architecture. And i am planning a release for all four generations of it.

**Comment by JasonBucotte** [comment]
Awesome, thanks!
